### ISSUE TITLE
VoiceForge voices not working after July 1st

### ISSUE THREAD

**Issue by duckduckstab1** [Windows81/GoAnimate-Wrapper#111]
Title says it all.

**Comment by Windows81** [comment]
Hi.  I'm not active with the Wrapper project anymore.  If you have a build with the VoiceForge voices either removed or fixed, feel free to let me know and I will make a pull request.

**Comment by duckduckstab1** [comment]
I'll try to fix it

**Comment by duckduckstab1** [comment]
What I know is that the mobile app is working ATM

**Comment by duckduckstab1** [comment]
The API now returns 401 Unauthorised so this is probably not gonna be fixed anytime soon, or so
Temporarily closing this.
