### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by ADILVLOGZ** [Windows81/GoAnimate-Wrapper#117]

**Comment by ADILVLOGZ** [comment]
Nice

**Comment by Windows81** [comment]
Thank you!

**Comment by ADILVLOGZ** [comment]
Yo, I really want to do wrapper offline

**Comment by Windows81** [comment]
Hey.  İf you want to contribute to Wrapper Offline, feel free to download the source and do some changes.  Make sure to extensively test them out before anything.  Then reach out to any of the Wrapper Offline people (not me) with those changes.

**Comment by ADILVLOGZ** [comment]
How do I do it though?

**Comment by Windows81** [comment]
Try downloading this file and changing what you want.  Then reach out to one of the developers and tell them what you did.  That's what I suggest if you're starting out.
https://github.com/Wrapper-Offline/Wrapper-Offline/archive/refs/heads/main.zip
